---
# This playbook deploys the cloudbox on a minimal installation.

- name: apply configuration to the cloudbox
  hosts: cloudboxes
  remote_user: ansible
  become: yes
  vars:
    if_lan: "enp1s0"
    ipaddr: "192.168.2.50/24"
    gateway: "192.168.2.1"
    DNS: "192.168.2.1"
    ddns_domain: "something.ddnss.de"
    ddns_updkey: "138638.some.key.here.635620"
    ansible_python_interpreter: "/usr/bin/python3"

  roles:
    - up2date-debian
#    - ddns-update
#    - low-power
    - nextcloud
