---
# This playbook deploys the cloudbox on a minimal installation.

- name: apply configuration to the cloudbox
  hosts: all
  remote_user: ansible
  become: Yes
  vars:
    if_lan: "enp1s0"
    ipaddr: "192.168.2.50/24"
    gateway: "192.168.2.1"
    DNS: "192.168.2.1"
    ddns_domain: "something.ddnss.de"
    ddns_updkey: "138638.some.key.here.635620"
    ## 'nc_download' and 'nc_checksum' are only
    ## used for ansible-pull during installation:
    nc_download: "https://download.nextcloud.com/server/releases/latest.tar.bz2"
    nc_checksum: "sha256:194095a5586d84040bc455f77b8aa6c80f9a6a6dd713c9aebdad046713d4267b"
    nc_apps:
      - calendar
      - notes
    backup_opts: "--exclude-caches -e '*/updater-*/' -e '*/preview/*' -e '*/files_trashbin/*'"
    backup_dirs:
      - "/etc"
      - "{{ nc_dir }}"
      - "{{ data_dir }}"
    ansible_python_interpreter: "/usr/bin/python3"

  roles:
    - up2date-debian
#    - ddns-update
#    - low-power
    - nextcloud
    - backup
