---
# This playbook deploys a kiosk-computer

- name: apply configuration to the machines
  hosts: kiosk-computers
  remote_user: ansible
  become: yes
  vars:
    auto_user: debi
    wifi_ssid: "YOUR SSID HERE"
    wifi_passwd: "YOUR WIFI-PW HERE"

  roles:
    - up2date-debian
    - gnome
    - kiosk
