---
# This playbook deploys a kiosk-computer

- name: apply configuration to the machines
  hosts: localhost
  remote_user: root
  vars:
    deb_release: "buster"
    auto_user: debi
    wifi_ssid: "YOUR SSID HERE"
    wifi_passwd: "YOUR WIFI-PW HERE"
    extra_pkgs:
      - unattended-upgrades
      - webext-privacy-badger
      - webext-ublock-origin
    extra_pkgs_bpo: []  # [ libreoffice ]

  roles:
    - up2date-debian
    - gnome
    - kiosk
