---
# This playbook does almost nothing.  Useful for testing only preseeding.

- name: apply a minimal configuration with kerberos LAN integration
  hosts: all
  remote_user: ansible
  become: yes
  roles:
    - up2date-debian
    - lan-client
